"use strict";
const nodemailer = require("nodemailer");
const {password} = require("./secrets")

// async..await is not allowed in global scope, must use a wrapper
async function mailSender() {
  // create reusable transporter object using the default SMTP transport
  let transporter = nodemailer.createTransport({
    host: "smtp.gmail.com",// Simple Mail Transfer Protocol (SMTP)
    port: 587,
    secure: false, // true for 465, false for other ports
    auth: {
      user: "bharathdarling970070@gmail.com", // generated ethereal user
      pass: password, // generated ethereal password
    },
  });

  // send mail with defined transport object
  let info = await transporter.sendMail({
    from: '"Fred Foo 👻" <foo@example.com>', // sender address
    to: "kurapati.ic19@nsut.ac.in, bharath999999@hotmail.com", // list of receivers
    subject: "Hello ✔", // Subject line
    text: "Hello world?", // plain text body
    html: "<b>Hello Ashish</b> <h1>This is an autogenerated mail using nodemailer</h1>", // html body
  });

  console.log("Message sent: %s", info.messageId);
  // Message sent: <b658f8ca-6296-ccf4-8306-87d57a0b4321@example.com>

  // Preview only available when sending through an Ethereal account
  console.log("Preview URL: %s", nodemailer.getTestMessageUrl(info));
  // Preview URL: https://ethereal.email/message/WaQKMgKddxQDoou...
}

mailSender().catch(console.error);
